@baseUri=http://127.0.0.1:8010/api 

### generate logo
POST {{baseUri}}/protected/gen-logo
Content-Type: application/json

{
    "description": "happy new year 2024"
}

### get logos
POST {{baseUri}}/get-logos
Content-Type: application/json

{
    "page": 1
}

### checkout
POST {{baseUri}}/checkout
Content-Type: application/json

{
    "page": 1
}


